import Link from "next/link";
import "./globals.css";
import Image from "next/image";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-black/10 flex min-h-screen flex-col items-center justify-start`}
      >
        <nav className="sticky top-0 z-50 flex flex-row w-full items-center justify-start bg-white">
          <div className="flex items-center w-32 h-32">
            <Link href="/">
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                priority
                width={128}
                height={29}
              />
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
